### ISSUE TITLE
Forced 2D view on Windows?

### ISSUE THREAD

**Issue by petersandor** [timkurvers/wowser#45]
After a while, I ran wowser (latest master updates) and saw this:

![wowser-latest](https://cloud.githubusercontent.com/assets/3933866/9098632/57f8323a-3bcb-11e5-9fc7-815134179378.jpg)

I couldn't interact at all. Any ideas about what's going on?

**Comment by timkurvers** [comment]
The orbit controls are currently missing after swapping to Riot as the UI framework. I probably should not have merged that in prematurely.

**Comment by timkurvers** [comment]
The forced perspective issue should be fixed in 5aa508ba5e95f80a5e9a4fc519ca43e0bc868054. Thanks!

**Comment by petersandor** [comment]
I'm still having the same problem even after update, I ran `gulp` and everything. Happens both in Chrome and Firefox

**Comment by timkurvers** [comment]
Does it still look skewed? Or are you thinking about the controls?

**Comment by petersandor** [comment]
Well basically I didn't register any change, I have the same top view and no controls as previously.

**Comment by timkurvers** [comment]
The controls are on the way, but the skewed view should be fixed. It's still from the top though.

**Comment by petersandor** [comment]
Ah sorry, you are right it's not skewed anymore.

**Comment by timkurvers** [comment]
The orbit controls should be back in with f3acd2c468d3877acf055ad6a9537948a9467323.

**Comment by petersandor** [comment]
Nice, thanks! Am closing this.
